
pipeline {
    agent any
    environment {
        IMAGE_NAME = 'zakariaallafou/auth-service'
        DOKCKER_CREDS = 'docker-hub-creds'
    }
    tools {
        maven 'M3'
        dockerTool 'docker'
    }

    stages {

        stage('Checkout Source Code') {
            steps {
                checkout scm 
            }
        }
        stage('Build Artifact'){
            steps {
                dir('auth-service'){
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        stage('Run Tests'){
            steps {
                dir('auth-service'){
                    sh 'mvn test'
                }
            }
        }
        stage('Docker Build & Push'){
            steps{
                script {
                    dir('auth-service') { 
                        // 1. Build l-image (Hadi khdama 100%)
                        sh "docker build -t ${IMAGE_NAME}:${env.BUILD_NUMBER} ."
                        
                        // 2. Login u Push b-tariqa compatible m3a ga3 l-versions
                        withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                            // Sta3melna -p f blasset --password-stdin
                            sh "docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}"
                            sh "docker push ${IMAGE_NAME}:${env.BUILD_NUMBER}"
                            sh "docker tag ${IMAGE_NAME}:${env.BUILD_NUMBER} ${IMAGE_NAME}:latest"
                            sh "docker push ${IMAGE_NAME}:latest"
                        }
                    }
                }
            }
        }
        stage('Deploy'){
            steps {
                // N-weqfo u n-msḥo l-container l-qdim (ila kan) u n-lanciwo jdid
                sh "docker stop auth-service || true && docker rm auth-service || true"
                sh "docker run -d -p 8082:8082 --name auth-service ${IMAGE_NAME}:${env.BUILD_NUMBER}"
            }
        }
    }
}